// react-markdown, rehype-sanitize, and their dependency tree are pure ESM packages.
// Jest's default transformIgnorePatterns skip node_modules, which breaks ESM imports.
// The pattern below tells Jest to transform these packages through ts-jest/babel
// so they can be required in the test environment.
const ESM_PACKAGES = [
  'react-markdown',
  'rehype-sanitize',
  'hast-util-sanitize',
  'hast-util-to-jsx-runtime',
  'hast-util-whitespace',
  'mdast-util-from-markdown',
  'mdast-util-to-hast',
  'mdast-util-to-markdown',
  'mdast-util-gfm',
  'mdast-util-gfm-autolink-literal',
  'mdast-util-gfm-footnote',
  'mdast-util-gfm-strikethrough',
  'mdast-util-gfm-table',
  'mdast-util-gfm-task-list-item',
  'mdast-util-find-and-replace',
  'mdast-util-phrasing',
  'mdast-util-to-string',
  'mdast-util-mdx-expression',
  'mdast-util-mdx-jsx',
  'mdast-util-mdxjs-esm',
  'micromark',
  'micromark-core-commonmark',
  'micromark-extension-gfm',
  'micromark-extension-gfm-autolink-literal',
  'micromark-extension-gfm-footnote',
  'micromark-extension-gfm-strikethrough',
  'micromark-extension-gfm-table',
  'micromark-extension-gfm-tagfilter',
  'micromark-extension-gfm-task-list-item',
  'micromark-factory-destination',
  'micromark-factory-label',
  'micromark-factory-space',
  'micromark-factory-title',
  'micromark-factory-whitespace',
  'micromark-util-character',
  'micromark-util-chunked',
  'micromark-util-classify-character',
  'micromark-util-combine-extensions',
  'micromark-util-decode-numeric-character-reference',
  'micromark-util-decode-string',
  'micromark-util-encode',
  'micromark-util-html-tag-name',
  'micromark-util-normalize-identifier',
  'micromark-util-resolve-all',
  'micromark-util-sanitize-uri',
  'micromark-util-subtokenize',
  'micromark-util-symbol',
  'micromark-util-types',
  'remark-gfm',
  'remark-parse',
  'remark-rehype',
  'remark-stringify',
  'unified',
  'trough',
  'bail',
  'vfile',
  'vfile-message',
  'unist-util-is',
  'unist-util-position',
  'unist-util-stringify-position',
  'unist-util-visit',
  'unist-util-visit-parents',
  'property-information',
  'space-separated-tokens',
  'comma-separated-tokens',
  'html-url-attributes',
  'decode-named-character-reference',
  'character-entities',
  'is-plain-obj',
  'devlop',
  'zwitch',
  'longest-streak',
  'stringify-entities',
  'character-entities-html4',
  'character-entities-legacy',
  'character-reference-invalid',
  'ccount',
  'escape-string-regexp',
  'estree-util-is-identifier-name',
  'trim-lines',
  'is-alphabetical',
  'is-alphanumerical',
  'is-decimal',
  'is-hexadecimal',
  'parse-entities',
  'index-to-position',
];

module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts', 'tsx'],
  rootDir: 'src',
  testRegex: '.*\\.(spec|test)\\.tsx?$',
  transform: {
    '^.+\\.tsx?$': ['ts-jest', { tsconfig: { jsx: 'react-jsx', esModuleInterop: true } }],
    '^.+\\.js$': ['ts-jest', { tsconfig: { jsx: 'react-jsx', esModuleInterop: true }, diagnostics: false }],
  },
  transformIgnorePatterns: [
    `/node_modules/(?!(${ESM_PACKAGES.join('|')})/)`,
  ],
  testEnvironment: 'node',
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/$1',
  },
};
