import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import Anthropic, { toFile } from '@anthropic-ai/sdk';
import { GeneratedText, LlmProvider, StreamEvent } from './llm-provider.interface';

const DEFAULT_MODEL = 'claude-opus-5';
// Output budget for one streaming turn. Includes thinking, tool_use inputs,
// and visible text — all share the same cap. With `thinking: adaptive`, the
// model routinely burns 2-4k tokens on reasoning before emitting anything,
// so a 4k cap left almost no room for tool_use blocks and caused silent
// `stop_reason: max_tokens` terminations mid-task. The Opus tier allows far
// larger outputs; 32k is the per-turn budget we hold it to, so large tool_use
// payloads (e.g. multi-row chronology appends) have room without the agent
// having to micro-batch. Large-chronology *creation* should still use the seed-empty +
// chronology_append loop — this cap raises the per-turn ceiling, it does not
// remove it.
const MAX_TOKENS = 32000;

@Injectable()
export class AnthropicProvider implements LlmProvider {
  private client: Anthropic;

  constructor(private readonly configService: ConfigService) {
    const apiKey = this.configService.get<string>('ANTHROPIC_API_KEY');
    this.client = new Anthropic({ apiKey });
  }

  async *streamChat(params: {
    system: Anthropic.Beta.BetaTextBlockParam[];
    messages: Anthropic.Beta.BetaMessageParam[];
    tools: Anthropic.Beta.BetaTool[];
    model?: string;
    containerId?: string;
  }): AsyncGenerator<StreamEvent> {
    // Cache the last tool definition — Anthropic caches everything up to and
    // including the last cache_control breakpoint, so this covers all tools.
    const tools = params.tools.map((tool, i) =>
      i === params.tools.length - 1
        ? { ...tool, cache_control: { type: 'ephemeral' as const } }
        : tool,
    );

    // Forward the container id when the previous turn under the
    // compact-2026-01-12 (programmatic tool calling) beta returned one.
    // Pending tool_use blocks generated inside a server-side code_execution
    // block can only be resolved against the same container — without this,
    // the next request fails with "container_id is required when there are
    // pending tool uses generated by code execution with tools."
    const stream = this.client.beta.messages.stream({
      betas: ['compact-2026-01-12', 'files-api-2025-04-14'],
      model: params.model ?? DEFAULT_MODEL,
      max_tokens: MAX_TOKENS,
      thinking: { type: 'adaptive' },
      system: params.system,
      messages: params.messages,
      tools,
      ...(params.containerId ? { container: params.containerId } : {}),
    } as Parameters<typeof this.client.beta.messages.stream>[0]);

    for await (const event of stream) {
      if (
        event.type === 'content_block_delta' &&
        event.delta.type === 'text_delta'
      ) {
        yield { type: 'text', content: event.delta.text };
      }
    }

    // Strip thinking / redacted_thinking blocks: we don't carry reasoning
    // across turns, and persisting them caused cache_control breakpoint bugs.
    //
    // Server-side tool blocks (server_tool_use + web_search_tool_result,
    // code_execution + code_execution_tool_result) MUST be preserved as
    // intra-message pairs. Stripping the use block while leaving its result —
    // or vice versa — produces orphaned blocks that the API rejects with a
    // 400 ("unexpected tool_use_id found in web_search_tool_result blocks ...
    // Each ... block must have a corresponding server_tool_use block before
    // it.") on the next replay of the conversation.
    const STRIP = new Set(['thinking', 'redacted_thinking']);
    const response = await stream.finalMessage();
    response.content = response.content.filter(
      (b) => !STRIP.has((b as { type: string }).type),
    ) as typeof response.content;
    yield { type: 'end_turn', response };
  }

  /**
   * Upload raw bytes to the Anthropic Files API and return the `file_id`.
   * Used for PDFs too large for an inline base64 `document` block (~4.5 MB).
   * The `files-api-2025-04-14` beta header is required on the upload AND on
   * every `messages.stream` that later references the returned `file_id`.
   */
  async uploadFile(buffer: Buffer, filename: string, mimeType: string): Promise<string> {
    const file = await this.client.beta.files.upload({
      file: await toFile(buffer, filename, { type: mimeType }),
      betas: ['files-api-2025-04-14'],
    });
    return file.id;
  }

  async generateText(params: {
    model?: string;
    maxTokens: number;
    messages: Anthropic.MessageParam[];
  }): Promise<GeneratedText> {
    const model = params.model ?? 'claude-haiku-4-5';
    const response = await this.client.messages.create({
      model,
      max_tokens: params.maxTokens,
      messages: params.messages,
    });
    const block = response.content[0];
    const text = block?.type === 'text' ? block.text.trim() : null;
    return { text, usage: response.usage, model };
  }

  /**
   * One-shot structured extraction via a forced tool call. The tool's
   * `input_schema` describes the desired output shape; `tool_choice` forces
   * the model to emit exactly one `tool_use` block matching it, so the caller
   * gets structured JSON without the fragility of parsing free-form text.
   * Non-streaming: extraction outputs are small, so no HTTP-timeout concern.
   */
  async extractJson(params: {
    model?: string;
    maxTokens: number;
    system?: string;
    messages: Anthropic.MessageParam[];
    tool: Anthropic.Tool; // schema of the desired output
  }): Promise<{ input: Record<string, unknown> | null; usage: Anthropic.Usage; model: string }> {
    const model = params.model ?? 'claude-sonnet-4-6';
    const response = await this.client.messages.create({
      model,
      max_tokens: params.maxTokens,
      system: params.system,
      messages: params.messages,
      tools: [params.tool],
      tool_choice: { type: 'tool', name: params.tool.name },
    });
    const block = response.content.find((b) => b.type === 'tool_use');
    return {
      input:
        block && block.type === 'tool_use'
          ? (block.input as Record<string, unknown>)
          : null,
      usage: response.usage,
      model,
    };
  }
}
