export { SKILL_NAMES, getSkillContent } from '../../../skills/skill-registry';
export {
  WEB_SEARCH_TOOL,
  GET_CASE_DATA_TOOL,
  GET_INVESTIGATION_TOOL,
  GET_SKILL_TOOL,
  EXECUTE_SCRIPT_TOOL,
  LIST_SCRIPT_RUNS_TOOL,
  QUERY_LABELED_ENTITIES_TOOL,
  CREATE_PRODUCTION_TOOL,
  READ_PRODUCTION_TOOL,
  UPDATE_PRODUCTION_TOOL,
} from './tool-definitions';
export {
  ADD_LABEL_TOOL,
  UPDATE_LABEL_TOOL,
  DELETE_LABEL_TOOL,
  MOVE_LABEL_TOOL,
  TETHER_LABEL_TOOL,
  LABEL_TOOLS,
} from './label-tools';

import {
  WEB_SEARCH_TOOL,
  GET_CASE_DATA_TOOL,
  GET_INVESTIGATION_TOOL,
  GET_SKILL_TOOL,
  EXECUTE_SCRIPT_TOOL,
  LIST_SCRIPT_RUNS_TOOL,
  QUERY_LABELED_ENTITIES_TOOL,
  CREATE_PRODUCTION_TOOL,
  READ_PRODUCTION_TOOL,
  UPDATE_PRODUCTION_TOOL,
} from './tool-definitions';
import { LABEL_TOOLS } from './label-tools';

export const AGENT_TOOLS = [
  WEB_SEARCH_TOOL,
  GET_CASE_DATA_TOOL,
  GET_INVESTIGATION_TOOL,
  GET_SKILL_TOOL,
  EXECUTE_SCRIPT_TOOL,
  LIST_SCRIPT_RUNS_TOOL,
  QUERY_LABELED_ENTITIES_TOOL,
  CREATE_PRODUCTION_TOOL,
  READ_PRODUCTION_TOOL,
  UPDATE_PRODUCTION_TOOL,
  ...LABEL_TOOLS,
];

export const READ_ONLY_AGENT_TOOLS = [
  WEB_SEARCH_TOOL,
  GET_CASE_DATA_TOOL,
  GET_INVESTIGATION_TOOL,
  GET_SKILL_TOOL,
  EXECUTE_SCRIPT_TOOL,
  LIST_SCRIPT_RUNS_TOOL,
  QUERY_LABELED_ENTITIES_TOOL,
  READ_PRODUCTION_TOOL,
];
